//! wolfxl-core: pure-Rust xlsx reader with Excel number-format-aware rendering.
//!
//! This crate carries no PyO3 / Python coupling. It opens xlsx workbooks via
//! [`calamine-styles`], exposes a `Workbook → Sheet → Cell` API, and renders
//! cell values with awareness of common Excel number formats (currency,
//! percentage, scientific, date, time).
//!
//! ```no_run
//! use wolfxl_core::Workbook;
//!
//! let mut wb = Workbook::open("examples/sample-financials.xlsx")?;
//! let sheet = wb.first_sheet()?;
//! let (rows, cols) = sheet.dimensions();
//! println!("{} rows × {} columns", rows, cols);
//! # Ok::<_, wolfxl_core::Error>(())
//! ```
//!
//! ## Scope
//!
//! - **In scope today:** read xlsx values + best-effort number-format strings,
//!   classify formats into [`FormatCategory`], render via [`format_cell`].
//! - **Not yet:** full `xl/styles.xml` cellXfs walker (style ids fall back to
//!   None for fixtures generated by openpyxl), schema inference, write side.
//!
//! The existing PyO3 layer in the sibling `wolfxl` cdylib still owns its own
//! implementation; unifying the two is follow-up work.

pub mod cell;
pub mod error;
pub mod format;
pub mod sheet;
pub mod workbook;

pub use cell::{Cell, CellValue};
pub use error::{Error, Result};
pub use format::{FormatCategory, format_cell};
pub use sheet::Sheet;
pub use workbook::Workbook;
