from __future__ import annotations

import os
import shutil
import zipfile
from pathlib import Path

import openpyxl
import pytest

import wolfxl

_FIXTURE_ENV = "WOLFXL_EXTERNAL_FIXTURES_DIR"
_MARKER_CELL = "Z1"
_MARKER_VALUE = "wolfxl_external_fixture_smoke"


def test_external_oracle_fixture_pack_preserves_existing_parts(tmp_path: Path) -> None:
    """Validate modify-save preservation over the optional ExcelBench fixture pack.

    The pack is generated by ExcelBench's external-oracle harness and currently
    includes workbooks authored by Excelize, ClosedXML, NPOI, ExcelJS, and
    Apache POI. The test is a local pre-release gate: it skips in isolated
    checkouts, but runs automatically when the sibling ExcelBench outputs exist
    or ``WOLFXL_EXTERNAL_FIXTURES_DIR`` points at a generated pack.
    """
    fixture_paths = _external_fixture_paths()
    if not fixture_paths:
        pytest.skip(
            "external oracle fixture pack not found; generate it in ExcelBench "
            "or set WOLFXL_EXTERNAL_FIXTURES_DIR"
        )

    for fixture_path in fixture_paths:
        _assert_modify_save_preserves_parts(fixture_path, tmp_path)


def _external_fixture_paths() -> list[Path]:
    fixture_dir = _fixture_dir()
    if not fixture_dir.is_dir():
        return []
    return sorted(
        path
        for path in fixture_dir.glob("*.xlsx")
        if path.is_file() and not path.name.startswith("~$")
    )


def _fixture_dir() -> Path:
    if env_path := os.environ.get(_FIXTURE_ENV):
        return Path(env_path).expanduser()
    project_root = Path(__file__).resolve().parents[1]
    projects_root = project_root.parent
    return projects_root / "ExcelBench" / "results_dev_external" / "fixtures"


def _assert_modify_save_preserves_parts(fixture_path: Path, tmp_path: Path) -> None:
    work_path = tmp_path / fixture_path.name
    shutil.copy2(fixture_path, work_path)

    before_parts = _zip_parts(work_path)
    workbook = wolfxl.load_workbook(work_path, modify=True)
    sheet_name = workbook.sheetnames[0]
    workbook[sheet_name][_MARKER_CELL] = _MARKER_VALUE
    workbook.save(work_path)
    workbook.close()

    after_parts = _zip_parts(work_path)
    missing_parts = before_parts - after_parts
    assert not missing_parts, (
        f"{fixture_path.name} lost existing OOXML parts during modify-save: "
        f"{sorted(missing_parts)}"
    )

    roundtrip = openpyxl.load_workbook(work_path, data_only=False)
    try:
        assert roundtrip[sheet_name][_MARKER_CELL].value == _MARKER_VALUE
    finally:
        roundtrip.close()

    with zipfile.ZipFile(work_path) as archive:
        assert archive.testzip() is None


def _zip_parts(path: Path) -> set[str]:
    with zipfile.ZipFile(path) as archive:
        return set(archive.namelist())
